### ISSUE TITLE
edit connect files

### ISSUE THREAD

**Issue by s53zo** [kconkas/dxspider-deployment#1]
Great idea to do a docker DXSpider, TNX!

How to edit the /spider/connect files? I found no editor that I know about (pico, nano, joe, vi)?

Also how do you forsee to update the DXSpider software when the new versions come out?

73
Simon, S53ZO

**Comment by kconkas** [comment]
@s53zo I've now included `vim.tiny` in the default image, as well as added detailed instructions how to copy files to/from the container. I hope you'll find this sufficient to maintain the `/spider/connect` files.

As for software upgrades, the idea is to simply stop the running docker container and start one with newer DXSpider version (but this will, of course, depend on whether a new DXSpider release itself will require any config changes etc.).
